language: node_js
node_js:
- stable
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: us-west-1
  app: AbleBox
  env: Ablebox-env
  on:
    branch: joseph
  bucket_name: elasticbeanstalk-us-west-1-027484451920
