language: node_js
node_js:
- stable
deploy:
  provider: elasticbeanstalk
  access_key_id: QWUvA7ahLm4SLKq69Y0lrlqDwbYqNmcXec75Q2MNuCb4mA5JrXL5ZzeeBmEWve0hxI6aPNsNBbQo/665vH5RlQ+O6M7FwzbMOB9GBV+xXQ9QcxAQ1vm9O7FVgPzP7AP+4zj2ZWbC25Toi/cmeIn9eVymZYt49JOmKSZUHGaSreR1PGS3g61R00lh0IQroJLfu0rTGaaFrZHbfsfWtsKVqLzLpY6cN9UMzLLH1rORDEzE6zF/tknU/H3S1wniZxR8QM7evZUM4FYIqaBu2yr4gE79qIjkxOkYTYht19rWnwb16sMJeZpL+hYvhEi7Cy7vm5nTHkpgWErSijmtTy8g117nqJRnGVnsesNWvwLZq1ms+HxAbeJVDXBSuKML7OIvZNlVe+TECuN33xCA2D/IrGNdKhcV8t1AYSD8U4JlY/ggf4OTkjqJwghUFAOMrLspW1J2JVzCs2ynFslw5rOqWoggZnNkN35e9mJJAEBuSvlU2zIEMm1P/7oH2ljI1ziC4yJD5rqazut+7MV0vgvwWCRDUxXGQsELO3wPSd82WJgAfU4OMAetv8Du8Q4eM+l6P25vsBrLHHR9tcf+6+tIIjawjPxqgwSgc0FOPo035BV9IOJcuET3/IqtQP5kB841QAWObuckh4FDc5ib+DUfi/d9aRMgZY0uotP7tqDzpJI=
  secret_access_key:
    secure: E9NUlitwHIqyR2Go2fYyM4bDB1648PvI1iSOZQc9zFH2pXuO5v5phfqKPWqkwjj8DOfxuDbzsOBGuYor/AfJb7Hl9kIIjIOmx0ETnHxSyclXwsRL1jdzzdRwE+UHj19olzw+uFeTnOU5vBhIpf+UxaVjyWnekCVcMl5+UNLi/uoyIfvisvkGK74edZSvk95tlLwlHQ4kxt3csvhekiVT5cWNhy9WDpqKgweOj4Stc2tzvKFTidNAa2wPl2x83PreBBgjQ/ZmZ8BdvNaA+cvgVHoeMXqS8Xe2D91VvQtJloNItps55cdxEKIcIKCpzqxnRVY4NwzIDp4dtoU6JuoTvvbmyCPqN5DdFHJcjuY1kYYEzgbYW2bdIE2SIMrx9J5DNICbNZtZvDNso/Vz916Bn4Bmqqdr3zxYC9t3AGlwrUfE75lSN0vSI6kuN9+pbqv+dE2rGM+Tbb8dT1lvP51Q5qwE7W2HGHwswFnUwIHY0mX9o8gKqrWjEzYNp1ba8iu7qqSZ3vsh4+2/HZ1BFZZEkE/1aXOx0gebqOT4nue5qpr1/wMCn1rTV4udvMvWMyMkBbZPBpGVJfn4DqBV8azcaFABivTHqegSPBHzZbUfOeELfWhoZ/rc8MLrwMnb1jGw7hqKnfDIAefOztP2gSU8SUNv0P3kLG+0iYG8nHndtF4=
  region: us-west-1
  app: AbleBox
  env: Ablebox-env
  on:
    branch: joseph
  bucket_name: elasticbeanstalk-us-west-1-027484451920
