DROP DATABASE IF EXISTS `ablebox`;

CREATE DATABASE `ablebox`;

USE `ablebox`;

DROP TABLE IF EXISTS `users`;

CREATE TABLE users (
  id MEDIUMINT(8) UNSIGNED AUTO_INCREMENT,
  email VARCHAR(200) NOT NULL,
  password CHAR(60) BINARY NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS `files`;

CREATE TABLE files (
  id MEDIUMINT(8) UNSIGNED AUTO_INCREMENT,
  user_id MEDIUMINT(8) UNSIGNED NOT NULL,
  folder_id MEDIUMINT(8) UNSIGNED DEFAULT 0,
  name VARCHAR(200) NOT NULL,
  file_ext VARCHAR(32) DEFAULT NULL,
  created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_folder TINYINT(1) NOT NULL DEFAULT 0,
  is_public TINYINT(1) NOT NULL DEFAULT 0,
  s3_objectId VARCHAR(400) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  INDEX (folder_id),
  INDEX (is_folder),
  INDEX (is_public)
);